version: "3.3"
services:
  holapay2-admin:
    stdin_open: true
    tty: true
    container_name: project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8066:8080"
    volumes:
      - ./:/app
      - /app/node_modules
